apiVersion: apps/v1
kind: Deployment
metadata:
   name: neatapp-deploy
   labels:
      name: neatapp-deploy
spec:
   replicas: 2
   selector:
      matchLabels:
         name: neatapp-pod
   template:
      metadata:
         name: neatapp-pod
         labels:
            name: neatapp-pod
      spec:
         containers:
         - name: neatapp-container
           image: chukmunnlee/neatstack:v2
           imagePullPolicy: IfNotPresent
           envFrom:
           - secretRef:
               name: neat-secret
           - configMapRef:
               name: neat-cm
           ports:
           - name: neatapp-port
             containerPort: 8080
           livenessProbe:
              exec:
                 command: [ "curl", "-f", "localhost:8080/api/healthz" ]
              initialDelaySeconds: 15
           resources:
              requests:
                 cpu: 100m
                 memory: 128Mi
           
---
apiVersion: v1
kind: Service
metadata:
   name: neatapp-svc
   labels:
      name: neatapp-svc
spec:
   type: ClusterIP
   selector:
      name: neatapp-pod
   ports:
   - name: neatapp-svc-port
     port: 8080
     targetPort: neatapp-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: neatapp-ing
   labels:
      name: neatapp-ing
   annotations:
      nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
   ingressClassName: nginx
   rules:
   - http:
         paths:
         - path: /
           pathType: Prefix
           backend:
              service:
                 name: neatapp-svc
                 port:
                    number: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
   name: neatapp-hpa
   labels:
      name: neatapp-hpa
spec:
   minReplicas: 1
   maxReplicas: 4
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: neatapp-deploy
   metrics:
   - type: Resource
     resource:
        name: memory
        target:
           type: Utilization
           averageUtilization: 80
   - type: Resource
     resource:
        name: cpu
        target:
           type: Utilization
           averageUtilization: 80
