# simple client using the Python SDK generated by openapi-generator-cli
# from backend/backend-api.yaml

import openapi_client

from openapi_client.api import default_api

# create a configuration 

config = openapi_client.Configuration(
      host='http://localhost:5000')

# load the client
with openapi_client.ApiClient(config) as client:
   # create an instance of the handle to the client
   handle = default_api.DefaultApi(client)

   # /api/kboards/fred
   result = handle.get_kboards_by_user_id('fred')

   print(result)

